### ISSUE TITLE
Cannot read property Flex of undefined

### ISSUE THREAD

**Issue by jordangarside** [gadicc/fview-flex#1]
After installing the package I get these 2 errors which break Meteor (Template and Meteor don't load).

```
Uncaught TypeError: Cannot read property 'utilities' of undefined   pre.js:29
Uncaught TypeError: Cannot read property 'Flex' of undefined        214af8c5953d4470adfaf43a65c7f97c2f0622d6:20
```

The utilities line is:

```
require = function(obj) {
  //console.log('r', obj);
  obj = obj.split('/');
  if (obj[0] === 'famous') {
    var s, ret = window;
    while (s=obj.shift())
      ret = ret[s];           //<---- Here
    return ret;
  }
```

The Flex line is:
`Flex = Package['gadicohen:fview-flex'].Flex;`

**Comment by jordangarside** [comment]
Closed because I didn't rtfm.
Waiting for support for raix:famono. :)

**Comment by gadicc** [comment]
there ya go :)

**Comment by jordangarside** [comment]
Awesome, thanks @gadicc! I'll have to show you what I've been working on soon. :)

**Comment by gadicc** [comment]
Please do :)  Very excited to see what people do with this... and as per the README, let me know if you need any missing functionality from upstream and I'll try prioritize it.

**Comment by jordangarside** [comment]
@gadicc Sorry I've been on vacation ><. Going to look more into Flex and everything soon. Here's my [famo.us based inlet](https://www.inlet.nu/cordova) (view it on a mobile device or in emulator). It still needs a lot of work.

**Comment by gadicc** [comment]
@jordangarside, that's great!  very solid start, looks like you're taking to all the libs quite naturally which not everyone manages :>

quite a lot of dropped frames, especially on mobile.  i wonder if it's from the reactivity.  let me know if the preview release from https://github.com/gadicc/meteor-famous-views/issues/215 makes a difference, and if it does, would love you to post a comparison on that page.

also, the famous-flex stuff is cached a lot better than (some of) the native famo.us views.  the original design principle was to recalculate EVERYTHING on every frame (at 60 fps), but the new paradigm more sensically is to cache computed values and only recalculate when needed.  some native famo.us stuff does this everywhere and some only in partial places... but the famous-flex stuff is very good on saving CPU cycles.

also, the lagometer takes up a little CPU time too.

**Comment by jordangarside** [comment]
@gadicc Thanks!

Currently the demo is non-reactive (Blaze.toHTML on templates) and is using JS Flex-Grid instead of FView Flex-Grid. I had the FView Flex-Grid in place, but when I ran into a couple issue I had to switch back (I needed support for sticky headers on the list view, which can be seen if you click on a trending thought).

Then there is the issue that I have a somewhat complicated nesting on the details page, managing which events get piped and whatnot:

```
Template.detailsCordova.rendered = ->
    detailsCordovaContainer = FView.byId('detailsCordovaContainer').view

    #Outer ScrollView
    headerScrollView = new Famous.FlexScrollView()
    headerScrollView.push new Famous.Surface
        size: [undefined, true]
        content: Blaze.toHTMLWithData(Template.detailsCordovaHeaderTitle)
        properties:
            backgroundColor: "black"
            zIndex: 5
    #Embdedded ScrollView
    contentScrollView = new Famous.FlexScrollView
        leadingScrollView: headerScrollView
        layoutOptions:
            isSectionCallback: (renderNode) ->
                #Need to check if renderNode is a surface
                if renderNode.properties?
                    return renderNode.properties.isSection

    #Embed Scrollview in Outer Scrollview
    headerScrollView.push(contentScrollView, undefined, false)
    #Create Sticky Header
    contentScrollView.push new Famous.Surface
            size: [undefined,true]
            content: Blaze.toHTMLWithData(Template.detailsCordovaStickyHeader)
            properties:
                backgroundColor: "black"
                boxShadow: "rgba(0, 0, 0, 0.74902) -1px 5px 5px 0px"
                isSection: true
                zIndex: 5
    window.contentScrollView = contentScrollView
    relationsScrollView = new Famous.FlexScrollView
        autoPipeEvents: true
        direction: Famous.Utilities.Direction.X
        overscroll: false
        paginated: true
        touchMoveDirectionThresshold: 0.5
    contentScrollView.push(detailsRenderController)

    window.inlet.horizontalScrollView = relationsScrollView

    argumentSurfaces = []
    acknowledgementSurfaces = []

    argumentsScrollView = new Famous.FlexScrollView
        autoPipeEvents: true
        leadingScrollView: contentScrollView
        touchMoveDirectionThresshold: 0.5
    window.argumentsScrollView = argumentsScrollView
    argumentsScrollView.pipe relationsScrollView
    acknowledgementsScrollView = new Famous.FlexScrollView
        autoPipeEvents: true
        leadingScrollView: contentScrollView
        touchMoveDirectionThresshold: 0.5
    acknowledgementsScrollView.pipe relationsScrollView

    relationsScrollView.push(argumentsScrollView)
    relationsScrollView.push(acknowledgementsScrollView)

    argumentsScrollView.setDataSource(argumentSurfaces)
    acknowledgementsScrollView.setDataSource(acknowledgementSurfaces)

    ...

    #Add OuterScrollView to Container
    detailsCordovaContainer.add headerScrollView
```

Wasn't sure of any easy way to manage something like this in FView and create the effect on that page that I want (try dragging the arguments up and swiping right-left).

...

Now, I'm dealing with the issue that I want to be able to do things with the back button and modals similar to how Angular handles pages (they cache the last 10 pages or so, so that there is no lag and page positioning isn't lost). Angular had a bunch of other problems for me (I hate how it manages routing and most of the functionality is rather restricting in how it can be used) so I steered away from it, but this is something I think that has to be managed for mobile.

So, I think the way to deal with this is to simply render all the important pages on load, then simply keep them in containers and transition them off the page instead of using RenderController as I am doing now (if there was some way to work functionality like this into RenderController that would be awesome and I think is almost necessary, but I don't know that it's a priority for them atm). I would then manage modal style pages by keeping say up to 5 of them off the page and doing all the routing/positioning myself, which has the added benefit that it is very app specific but means I have to do a lot of intro work.

I'm basically ignoring the dropped frames for now while I straddle the line of sanity. :p

**Comment by gadicc** [comment]
Haha ok that is quite involved... will try look at it when I get a chance, but have a few other higher priorities for now.  I'd definitely love to provide an fview pattern for complicated layouts though.  is the project open source and is their a repo I can play with?  although as mentioned won't have time for a while.

I'll probably do sticky header support next in fviews as soon as I can, which I'll track here: https://github.com/gadicc/fview-flex/issues/3

It wouldn't be hard for me to make RenderController support a more famo.us pattern, if you want to handle routing yourself.  Something like:

``` jade
+RenderController id="mainRC"
  +Surface id="s1"
  +Surface id="s2"
```

``` js
FView.byId("mainRC").show("s1");
```

Otherwise, the suggestions you made for iron-router are I think good and would be useful implementing at some point.  Unfortunately I suspect they also have higher priorities for now.  I haven't actually noticed much lag in the current implementation, but I guess it would be more noticeable on older devices.  There are also issues to think about like subscription management, waitOn, etc for preloaded pages.

**Comment by jordangarside** [comment]
@gadicc Sorry for being away, I still have this very much on my mind, I'm just doing a couple things right now. I should be back on this Tuesday.

I'm thinking it would be nice to have a Famous RouteManager or something along those lines that would support different transitions and sets of surfaces (cards) and manage stacks of surfaces so this history could be tracked and the cards/surfaces could be closed similar to how Google Music works.

If done correctly it should be much more effective than Google's current implementation of routing in angular (which has lag when closing a card/pressing back button or opening a new page). Their implementation can be viewed in Google Music, Gmail, Hangouts, etc...

I'll probably make a repo within the next week or so that's open source with just the skeleton to demonstrate these aspects as well as fview-flex.
