### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by Wenape** [gadicc/fview-flex#5]
Whenever an item is changed/inserted/removed inside the FlexScrollView, I get the following error:

```
Uncaught TypeError: Cannot read property 'add' of null       ContainerSurface.js:5
FView.ready.FView.registerView.add                           ContainerSurface.js:5
(anonymous function)                                         famous.js:251
step                                                         famous-global.js:375
loop                                                         famous-global.js:383
```

I've tried the following:

```
 {{#ContainerSurface perspective=500 translate='[0, 0, 2]'}}
   {{#FlexScrollView layout="ListLayout" direction="Y" layoutOptions='{ "marigns": 0, "spacing": 0 }'}}

    {{>View id='MainOb' template="MainOb" size='[undefined, 240]' translate='[0, 0, 2]'}}

    {{#famousEach normalObs}}
      {{>View template="nOb" id=this._id size='[undefined, 120]' opacity=0 translate='[0, 0, 1]'}}
    {{/famousEach}}

  {{/FlexScrollView}}
{{/ContainerSurface}}
```

I've tried the same:
  1) Without a ContainerSurface
  2) Including the "itemSize" option

I always get the same error for some reason.

**Comment by Wenape** [comment]
Apparently this error still happens. It seems using views within the children of `famousEach` is problematic. Most of the times the initial documents do render, but any subsequent update to the collection ends up with this error.

**Comment by gadicc** [comment]
I've actually been revamping the famousEach code over the last few days... can you see if `0.1.33-pre.1` makes any difference?  Otherwise if you can make a full repro with data that would be great.

**Comment by Wenape** [comment]
`0.1.33-pre.1` fixed it, Thanks.
