### ISSUE TITLE
should call function on FlexScrollView

### ISSUE THREAD

**Issue by neonaleon** [gadicc/fview-flex#6]
https://github.com/gadicc/fview-flex/blob/master/lib/FlexScrollView.js#L86

return this.setLayout(value);

should probably be 

return this.view.setLayout(value);

**Comment by gadicc** [comment]
You're right of course :>  @ShawnOceanHu fixed this in https://github.com/gadicc/fview-flex/pull/9, which was published in v0.0.5 on Mar 27th.  Sorry we didn't link back into this issue.
