### ISSUE TITLE
Add fview-flex HeaderFooterLayout

### ISSUE THREAD

**Issue by groblochon** [gadicc/fview-flex#8]
Hi,

I'm looking for an animated headerFooterLayout and the fview-flex one seem better to do this :  
http://www.tagwith.com/question_219140_is-there-a-way-to-animate-the-size-of-the-header-in-the-headerfooterlayout

Thank for your work !

**Comment by BodhiHu** [comment]
Hi I just made a PR which included support for HeaderFooterLayout: https://github.com/gadicc/fview-flex/pull/9

**Comment by groblochon** [comment]
Thanks, it's working like a charm !
